lfs_project/lfs/urls.py
from django.conf.urls import patterns, url, include
from lfs import views
from lfs_quiz.views import QuizDetailView, QuizTake
from django.views.generic import TemplateView

# from django.contrib.auth.views import *

urlpatterns = patterns('',
                       # Basic user navigation
                       url(r'^$', views.user_dashboard, name='index'),
                       url(r'^register/$', views.user_register, name="register"),
                       url(r'^login/$', views.user_login, name="login"),
                       url(r'^logout/$', views.user_logout, name="logout"),
                       url(r'^dashboard/$', views.user_dashboard, name="dashboard"),
                       url(r'^profile/(?P<userid>[\w\-]+)/$', views.profile, name="profile"),
                       url(r'^profile/(?P<userid>[\w\-]+)/edit/$', views.edit_profile, name="edit_profile"),
                       url(r'^forum/$', views.forum, name="forum"),
                       url(r'^contact_admin/(?P<userid>[\w\-]+)$', views.user_contact_admin, name="contact_admin"),
                       url(r'^leaderboard/$', views.leaderboard, name="leaderboard"),
                       url(r'^admin_guide/$', views.admin_guide, name="admin_guide"),
                       url(r'^subscription/(?P<userid>[\w\-]+)$', views.user_subscription, name="subscription"),
                       url(r'^change_password/$', views.change_password, name="change_password"),
                       url(r'^update_progress/(?P<moduleid>[\w\-]+)/(?P<pagenum>[\w\-]+)$', views.update_progress,
                           name="update_progress"),

                       # Modules functionality
                       url(r'^modules/$', views.modules, name="modules"),
                       url(r'^download/(?P<contentid>[\w\-]+)$', views.download_content, name="download_content"),
                       url(r'^module/(?P<moduleid>[\w\-]+)/$', views.module, name="module"),
                       url(r'^module/(?P<moduleid>[\w\-]+)/quiz/$', view=QuizDetailView.as_view(),
                           name='quiz_start_page'),
                       url(r'^module/(?P<moduleid>[\w\-]+)/quiz/take$', view=QuizTake.as_view(), name='quiz_question'),
                       url(r'^pick_module/(?P<moduleid>[\w\-]+)/$', views.pick_module, name="pick_module"),
                       url(r'^drop_module/(?P<moduleid>[\w\-]+)/$', views.drop_module, name="drop_module"),

                       # Trial functionality
                       url(r'^trial/$', views.trial_dashboard, name="trial_dashboard"),
                       url(r'^trial/module/(?P<moduleid>[\w\-]+)/$', views.trial_module, name="trial_module"),

                       # Messaging functionality
                       url(r'^messages/(?P<userid>[\w\-]+)$', views.user_messages, name="messages"),
                       url(r'^messages/(?P<messageid>[\w\-]+)$', views.message, name="message"),
                       url(r'^messages/(?P<messageid>[\w\-]+)/send/$', views.message_send, name="send_message"),

                       )

lfs_project/lfs_project/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin

urlpatterns = patterns('',

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^lfs/', include('lfs.urls')),
                       url(r'^lfs_admin/', include('lfs_admin.urls')),
                       url(r'^lfs_quiz/', include('lfs_quiz.urls')),
                       url(r'^forum/', include('pybb.urls', namespace='pybb')),
                       )

lfs_project/lfs/models.py
from __future__ import unicode_literals
import os

from django.db import models
from django.contrib.auth.models import User
from hitcount.models import HitCountMixin


class Teacher(models.Model):
    """ Representing teacher in database, subclass of User. """
    user = models.OneToOneField(User)

    # Additional fields to save more info about teacher
    bio = models.CharField(max_length=500, default='')
    school = models.CharField(max_length=200, default='')
    AGE_RANGE_CHOICES = (
        ('0', '16-21'),
        ('1', '22-28'),
        ('2', '29-35'),
        ('3', '36-42'),
        ('4', '42-48'),
        ('5', '49-55'),
        ('6', '56 or older'),
    )
    age_range = models.CharField(max_length=2,
                                 choices=AGE_RANGE_CHOICES,
                                 default='0')
    location = models.CharField(max_length=200, default='')
    picture = models.ImageField(upload_to='static/Pictures/', blank=True)
    # opt in to leaderboard
    leaderboard = models.BooleanField(default=True)

    def __unicode__(self):
        return self.user.username


class Module(models.Model, HitCountMixin):
    """ Representing modules, have many to many relationship with teachers,
        this relationship is expressed through Takers class, so it's possible
        to save progress for action """
    taker = models.ManyToManyField(User, through='Takers')

    title = models.CharField(max_length=200)
    background = models.ImageField(upload_to='static/Pictures/', blank=True)
    # downloadable = models.FileField(upload_to='Content/', blank=True)

    trial = models.BooleanField(default=False)
    compulsory = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title


class ContentFile(models.Model):
    """ Represents a downloadable file """
    module = models.ForeignKey(Module)
    file = models.FileField(upload_to='Content/', blank=True)
    clicks = models.IntegerField(default=0)

    def filename(self):
        return os.path.basename(self.file.name)


class Takers(models.Model):
    """ Many to many representation between Modules and Teachers. """
    user = models.ForeignKey(User)
    module = models.ForeignKey(Module)

    progress = models.IntegerField(default=0)

    def __unicode__(self):
        return self.user.username + self.module.title


class Page(models.Model):
    module = models.ForeignKey(Module)

    position = models.IntegerField(default=0)  # order of page
    section = models.CharField(max_length=200)  # title of section
    content = models.TextField()

    # Maintain table order by insertion time
    time = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ['time']

    def __unicode__(self):
        return self.section


# Workaround to storing dictionaries as fields

class ModuleVideo(models.Model):
    module = models.ForeignKey(Module)

    video = models.FileField(upload_to='ModuleVideos/')


class PageVideo(models.Model):
    page = models.ForeignKey(Page)

    video = models.FileField(upload_to='PageVideos/')


class Picture(models.Model):
    page = models.ForeignKey(Page)

    picture = models.ImageField(upload_to='Pictures/', blank=True)

lfs_project/lfs/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import ObjectDoesNotExist
from lfs.models import Teacher, Takers, Module, Page, ContentFile
from lfs_admin.models import Administrator, UserRegistrations, AnonHits
from lfs.forms import UserForm, TeacherForm
from wsgiref.util import FileWrapper
from hitcount.models import HitCount
from hitcount.views import HitCountMixin
from datetime import date

import os

# Logg stuff
import logging

logging.basicConfig(filename='wtf.log', level=logging.INFO)
logger = logging.getLogger(__name__)


# ---------------------- Basic User Navigation --------------------


def user_register(request):
    """ User registration """

    context_dict = {}

    # pass which navbar tab is active
    context_dict['nbar'] = 'register'

    context_dict['user_form'] = UserForm()
    context_dict['teacher_form'] = TeacherForm()
    context_dict['is_admin'] = False

    # check if user is admin
    if request.user.is_authenticated():
        if Administrator.objects.filter(user=request.user).exists():
            context_dict['is_admin'] = True

    if request.method == 'POST':
        form = UserForm(request.POST)
        # Django's default User model

        if form.is_valid():
            try:
                user = User.objects.create_user(form.cleaned_data['username'],
                                                form.cleaned_data['email'],
                                                form.cleaned_data['password'],
                                                first_name=form.cleaned_data['first_name'],
                                                last_name=form.cleaned_data['last_name'])
            except ValueError:
                # user left an invalid/empty field
                # TODO: Add an error message/indicator for users
                return render(request, 'lfs/login/register.html', {})

            # Use default (empty values) for all other Teacher fields
            Teacher.objects.create(user=user)

            for module in Module.objects.filter(compulsory=True):
                Takers.objects.create(user=user, module=module)

            # Record this registration for statistics
            UserRegistrations.objects.get_or_create(time=date.today())[0].inc()

            return HttpResponseRedirect('/lfs/login/')
        else:
            context_dict['errors'] = form.errors
            print form.errors

    return render(request, 'lfs/login/register.html', context_dict)


def user_login(request):
    """ User login """

    context_dict = {}
    context_dict['nbar'] = 'login'

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                # this acc is active
                login(request, user)
                # Redirect to dashboard once page is finished
                return HttpResponseRedirect('/lfs/dashboard/')

            else:
                # acc inactive
                return HttpResponse('Inactive acount')

        else:
            # bad details
            context_dict['errors'] = 'Please enter valid login details'
            return render(request, 'lfs/login/login.html', context_dict)

    else:
        # GET -> display dashboard
        # also record anon user
        if not request.user.is_authenticated():
            # Record this anon user for statistics
            AnonHits.objects.get_or_create(time=date.today())[0].inc()
        return render(request, 'lfs/login/login.html', context_dict)


@login_required
def user_logout(request):
    """ User logout """
    logout(request)

    return HttpResponseRedirect('/lfs/login/')


@login_required
def user_dashboard(request):
    """ User dashboard with all selected modules """
    context_dict = {}
    context_dict['is_admin'] = False

    # check if user is logged in
    if request.user.is_authenticated():
        user = request.user
        # check if user is an admin
        if Administrator.objects.filter(user=user).exists():
            context_dict['is_admin'] = True

    # pass which navbar tab is active
    context_dict['nbar'] = 'home'

    # get currently logged in user
    user = request.user
    if not user.is_staff:
        teacher = Teacher.objects.filter(user=user)[0]
        context_dict['teacher'] = teacher

    takers_record = Takers.objects.all()
    # teacher's overall progress =
    # (sum of progress in all modules / # modules taken)
    modules_taken_count = takers_record.filter(user=user).count()
    if modules_taken_count != 0:
        context_dict['overall_progress'] = reduce(lambda x, y: x + y,
                                                  [i.progress for i in takers_record if i.user == user],
                                                  0) / modules_taken_count
    else:
        context_dict['overall_progress'] = 0

    # pass all modules taken by user as a dict(module_name : progress)
    context_dict['modules_progress'] = {i.module: i.progress for i in takers_record if i.user == user}
    if context_dict['is_admin']:
        context_dict['modules_progress'] = {i: 0 for i in Module.objects.all()}
        for i in Module.objects.all():
            Takers.objects.get_or_create(user=user, module=i)
        context_dict['overall_progress'] = 0

    # also pass total number of modules available throughout the platform
    context_dict['modules_total'] = Module.objects.all().count()

    # completed modules
    context_dict['modules_completed'] = {i.module: i.progress for i in takers_record if
                                         i.user == user and i.progress == 100}

    # also pass if admin

    return render(request, 'lfs/index.html', context_dict)


@login_required
def user_contact_admin(request, userid):
    """ User contacts an admin """
    pass


@login_required
def leaderboard(request):
    """ Website leaderboard containing 'all' users """
    """ add top 20 users with progress """
    context_dict = {}

    # pass which navbar tab is active
    context_dict['nbar'] = 'leaderboard'

    user = request.user
    if not user.is_staff:
        teacher = Teacher.objects.filter(user=user)[0]
        context_dict['teacher'] = teacher
    all_users = User.objects.all()

    takers_record = Takers.objects.all()
    # teacher's overall progress =
    # (sum of progress in all modules / # modules taken)
    modules_taken_count = takers_record.filter(user=user).count()
    if modules_taken_count != 0:
        context_dict['overall_progress'] = reduce(lambda x, y: x + y,
                                                  [i.progress for i in takers_record if i.user == user],
                                                  0) / modules_taken_count
    else:
        context_dict['overall_progress'] = 0

    all_modules = Module.objects.all()
    # pass all modules as a dict with dict(module_name : [(name, progress)])
    context_dict['leaderboards'] = {str(i.title): [(j.user, j.progress) for j in takers_record if j.module == i] for i
                                    in all_modules}

    # also pass total number of modules available throughout the platform
    context_dict['modules_total'] = Module.objects.all().count()

    # completed modules
    context_dict['modules_completed'] = {i.module: i.progress for i in takers_record if
                                         i.user == user and i.progress == 100}

    # pass per-user overall progress as:
    # { username : overall_progress }
    context_dict['all_users_overall_progress'] = {}

    for j in all_users:
        modules_taken_count = takers_record.filter(user=j).count()
        if modules_taken_count != 0:
            context_dict['all_users_overall_progress'].update({j: reduce(lambda x, y: x + y,
                                                                         [i.progress for i in takers_record if
                                                                          i.user == j], 0) / modules_taken_count})

        else:
            context_dict['all_users_overall_progress'].update({j: 0})

    return render(request, 'lfs/leaderboard.html', context_dict)


def profile(request, userid):
    """ Profile of selected user """
    context_dict = {}

    # pass which navbar tab is active
    context_dict['nbar'] = 'profile'

    user = User.objects.get(id=userid)
    context_dict['profile_user_id'] = user.id

    # add user details to the context dictionary
    if not user.is_staff:
        context_dict.update(get_profileDetails(request, user.username))
        teacher = Teacher.objects.filter(user=user)[0]
        context_dict['teacher'] = teacher

    takers_record = Takers.objects.all()
    # teacher's overall progress =
    # (sum of progress in all modules / # modules taken)
    modules_taken_count = takers_record.filter(user=user).count()
    if modules_taken_count != 0:
        context_dict['overall_progress'] = reduce(lambda x, y: x + y,
                                                  [i.progress for i in takers_record if i.user == user],
                                                  0) / modules_taken_count
    else:
        context_dict['overall_progress'] = 0

    # pass all modules taken by user as a dict(module_name : progress)
    context_dict['modules_progress'] = {str(i.module.title): i.progress for i in takers_record if i.user == user}

    # also pass total number of modules available throughout the platform
    context_dict['modules_total'] = Module.objects.all().count()

lfs_project/templates/lfs/admin_stats.html
{% extends 'lfs/base.html' %}
{% load staticfiles %}
{% block title %}Content{% endblock %}
{% block body_block %}
<div class="container">
  <div class="row">
    <style>
      .bar {
        fill: steelblue;
      }

      .bar:hover {
        fill: brown;
      }

      .axis {
        font: 10px sans-serif;
      }

      .axis path,
      .axis line {
        fill: none;
        stroke: #000;
        shape-rendering: crispEdges;
      }

      .x.axis path {
        display: none;
      }

      .line {
        fill: none;
        stroke: steelblue;
        stroke-width: 1.5px;
      }
    </style>

    <script src="//d3js.org/d3.v3.min.js"></script>
    <script src="{% static 'js/admin_stats.js' %}" type="text/javascript"></script>
    <script>
      var modules_data={{ modules_data|safe }};
      var regs_data={{ regs_data|safe }};
      var anon_hits_data={{ anon_hits_data|safe }};
      
      gen_modules_barchart(modules_data);
      gen_regs_linechart(regs_data);
      gen_anon_hits_linechart(anon_hits_data);
    </script>
   
  </div> <!--/.row-->
</div> <!--/.container-->
{% endblock %}

lfs_project/templates/lfs/content.html
{% extends 'lfs/base.html' %}
{% load staticfiles %}
{% block title %}Content{% endblock %}
{% block body_block %}

<script src="{% static 'js/contentpage.js' %}" type="text/javascript"></script>

  <div class="container">
    <div class="row">
      <div class="col-md-9 col-xs-8 border content-box">
          <!-- main body -->
          <h1>{{ module_title }}</h1>
          {% for p in pages %}
          <div hidden id="moduleid" value="{{module_id}}"></div>
          <div class="module-page" id="page{{p.position}}" >
            <h2>{{ p }}</h2>
            <hr>
            
            <div class="mt5">
              <p> {{ p.content|safe }} </p>
            </div>
          </div>
          {% endfor %}
          <ul>
            {% for dw_item in module_downloadable %}
              <li><a class="downloadables"  href="{% url 'download_content' dw_item.id %}">{{ dw_item.filename }}</a>
        		{% if is_admin %}
        		  downloads: {{ dw_item.clicks }}
        		{% endif %}
        	      </li>
                    {% endfor %}
                  </ul>
        	  {% if is_admin %}
        	    <a>User Visits: {{visits}}</a>
        	  {% endif %}
	           <div class="row mt5">
                <div class="col-md-9 col-xs-9">
                  <a id="back-btn" href="{% url 'index' %}" type="button" class="btn btn-prim"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Back</a>
                  <a id="prev-page" type="button" class="btn btn-prim"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Back</a>
                  {% if is_admin %}
                    <a href="{% url 'edit_module' module_id %}" type="button" class="btn btn-prim"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit Module</a>
                  {% endif %}
                </div><!-- ./col-md-10-->

                <div class="col-md-3 col-xs-3">
                  <a id="quiz-btn" href="{% url 'quiz_start_page' module_id %}" type="button" class="btn btn-prim">Quiz<span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                  <a id="next-page" type="button" class="btn btn-prim">Next <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                </div><!-- ./col-md-2-->
            </div><!-- ./row -->

      </div><!-- ./content-box-->

{% block sidebar %}

      <div class="col-md-3 col-xs-4 sidebar sidebar-bkgr" align="center">
        <!-- sidebar -->
        </br>
        <h2>Progress of Module</h2>
        <div class="circle sidebar-circle" id="sidebar_circle">
          <p id="sidebar_circle_percentage">{{ user_progress_on_module }}%</p>
        </div>
        <script>
            $('#sidebar_circle').circleProgress({
                startAngle: -Math.PI/2,
                reverse: true,
                value: {{ user_progress_on_module }}/100,
                size: 150,
                thickness: 20,
                fill: {
                    gradient: ["green", "green"]
                }
            });
        </script>

        <!--tabs-->
        <ul class="nav nav-tabs" id="module-tabs">
          {% for mod in user_modules %}
            {% if mod.title == module_title %}
              <li class="active"><a data-toggle="tab" href='#tab-{{ mod.id }}'
              data-toggle="tab">{{ forloop.counter }}.{{ mod.title }}</a></li>
            {% else %}
              <li><a href='#tab-{{ mod.id }}'
              data-toggle="tab">{{ forloop.counter }}.{{ mod.title }}</a></li>
            {% endif %}
          {% endfor %}
          </ul><!-- ./nav-tabs -->
          <div class="tab-content">
            {% for mod in user_modules %}
              <div {% if mod.title == module_title %}
                class="tab-pane fade in active"
              {% else %}
                class="tab-pane fade"
              {% endif %}
              id='tab-{{ mod.id }}' align="left">
              <!-- {% if mod.title == module_title %} -->
              <!-- <div class="tab-pane fade in active" id='tab-{{ mod.id }}' align="left"> -->
              <!-- {% else %} -->
              <!-- <div class="tab-pane fade" id='tab-{{ mod.id }}' align="left"> -->
              <!-- {% endif %} -->
                <ul>
                  {% for modpage in mod.page_set.all %}
                    <li>Section {{ forloop.counter }}: {{ modpage.section }}</li>
                  {% endfor %}
                  <li>Quiz</li>
                </ul>
              </div><!-- ./tab-pane-->
            {% endfor %}
          </div><!-- ./tab-content -->
        </div>  <!-- ./sidebar -->

{% endblock %}

      </div> <!--/.row-->
    </div> <!--/.container-->
  {% endblock %}

lfs_project/templates/lfs/forum.html
{% extends 'lfs/base.html' %}

{% load staticfiles %}

{% block title %}Forum{% endblock %}

{% block body_block %}

<div class="container">

   <div class="row">

     <div class="col-md-9 col-xs-8">
       <!-- main body -->
       <h2>Forum</h2>
       <hr>

     </div><!--./col-md-9-->

{% block sidebar %} {{ block.super }} {% endblock %}

   </div> <!--/.row-->

 </div> <!--/.container-->

{% endblock %}

lfs_project/templates/lfs/leaderboard.html
{% extends 'lfs/base.html' %}

{% load staticfiles %}

{% block title %}Leaderboard{% endblock %}

{% block body_block %}

<!-- css/js for datatables -->
<link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
<script src="{% static 'js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/leaderboards.js' %}" type="text/javascript"></script>

<div class="container">

   <div class="row">

     <div class="col-md-9 col-xs-8">
       <!-- main body -->
       <div class="row">
          <div class="col-md-12">
            <h2 id="title" align="center">Overall</h2>
            <hr>

          </div><!--./col-md-12-->


          <div class="col-md-3 col-xs-4 sidebar sidebar-bkgr" align="center">
             <!-- sidebar -->
              </br>
              <h2>Progress</h2>
              <div class="circle sidebar-circle" id="sidebar_circle">
                <p>{{ overall_progress }}%</p>
              </div>
              <script>
                  $('#sidebar_circle').circleProgress({
                      startAngle: -Math.PI/2,
                      reverse: true,
                      value: {{ overall_progress }}/100,
                      size: 150,
                      thickness: 20,
                      fill: {
                          gradient: ["green", "green"]
                      }
                  });
              </script>
              <h4> Select Module </h4>
              <select id="category-select">
                <option value="Overall" data-target="0">Overall</option>
                {% for key, value in leaderboards.items %}
                  <option value="{{key}}" data-target="{{forloop.counter}}">{{key}}</option>
                {% endfor %}
              </select>

              <h4>{{ teacher.user.first_name }} {{ teacher.user.last_name }}'s stats</h4>
              <div class="panel panel-default">
                <div class="panel-body" align="left">
                  <h5>Total modules: {{ modules_total }} </h5>
                  <h5>Total taken: {{ modules_progress|length }} </h5>
                  <h5>Total complete: 6 </h5>
                  <h5>Mistakes made: 22 </h5>
                </div><!-- ./panel-body -->
              </div><!-- ./panel -->

        </div>	<!-- ./sidebar -->

        </div> <!--/.row-->


  {% if user.teacher.leaderboard %}
  <p>Note: You can opt out of the leaderboard in the <a href="{% url 'edit_profile' teacher.user.id %}">edit profile page</a><p>
  <table id="table_id" class="display mydisplay">
    <thead>
        <tr>
            <th>Name</th>
            <th>Progress</th>
            <th>Location</th>
            <th>Age Range</th>
            <th>Category</th>
        </tr>
      </thead>
      <tbody>
      {% for key, value in all_users_overall_progress.items %}
      {% if key.teacher.leaderboard %}
      <tr>
        {% if teacher.user.id == key.id %}
          <td id="currentuser">
              <a class="leaderboard-name" href="{% url 'profile' key.id %}">{{key}}</a>
          </td>
          <td id="currentuser">
            <div class="progress" id="leaderboard-progress-bar">
                <div class="progress-bar progress-bar-success leaderboard-progress" role="progressbar" aria-valuenow="{{ value }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ value }}%;">
                         {{ value }}
                </div><!--./progress-bar-->
            </div><!--./progress-->
          </td>
          <td id="currentuser">{{key.teacher.school}}</td>
          <td id="currentuser">{{key.teacher.get_age_range_display}}</td>
          <td id="currentuser">Overall</td>
        {% else %}
          <td>
            <a class="leaderboard-name" href="{% url 'profile' key.id %}">{{key}}</a>
          </td>
          <!--<td>{{value}}</td>-->
          <td>
            <div class="progress" id="module-progress">
                <div class="progress-bar progress-bar-success leaderboard-progress"role="progressbar" aria-valuenow="{{ value }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ value }}%;">
                         {{ value }}
                </div><!--./progress-bar-->
            </div><!--./progress-->
          </td>
          <td>{{key.teacher.school}}</td>
          <td>{{key.teacher.get_age_range_display}}</td>
          <td>Overall</td>
        {% endif %}
      </tr>
      {% endif %}
      {% endfor %}

      {% for category, usertuple in leaderboards.items %}
      {% for takeruser, progress in usertuple %}
      {% if takeruser.teacher.leaderboard %}
      <tr>
        {% if teacher.user == takeruser %}
          <td id="currentuser"><a class="leaderboard-name" href="{% url 'profile' takeruser.id %}">{{takeruser}}</a></td>
          <td id="currentuser" >
            <div class="progress" id="leaderboard-progress-bar">
                <div class="progress-bar progress-bar-success leaderboard-progress" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%;">
                         {{ progress }}
                </div><!--./progress-bar-->
            </div><!--./progress-->
          </td>
          <td id="currentuser">{{takeruser.teacher.school}}</td>
          <td id="currentuser">{{takeruser.teacher.get_age_range_display}}</td>
          <td id="currentuser">{{category}}</td>
        {% else %}
          <td><a class="leaderboard-name" href="{% url 'profile' takeruser.id %}">{{takeruser}}</a></td>
          <td>
            <div class="progress" id="module-progress">
                <div class="progress-bar progress-bar-success leaderboard-progress"role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%;">
                         {{ progress }}
                </div><!--./progress-bar-->
            </div><!--./progress-->
            </div><!--./progress-->
          </td>
          <td>{{takeruser.teacher.school}}</td>
          <td>{{takeruser.teacher.get_age_range_display}}</td>
          <td>{{category}}</td>
        {% endif %}
      </tr>
      {% endif %}
      {% endfor %}
      {% endfor %}
      </tbody>
    </table>
    {% else %}
      <h4>You must opt in to the leaderboards to view them.</h4>
      <p>You can do this in <a href="{% url 'edit_profile' teacher.user.id %}">edit profile page</a></p>
    {% endif %}

      </div><!-- ./col-md-9 -->
    </div><!-- ./row -->
 </div> <!--/.container-->
{% endblock %}